import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://shop.deutschepost.de/shop/nachsenden-lagern/nachsendeservice.jsp');
  await page.getByRole('button', { name: 'Alle akzeptieren' }).click();
  await page.getByRole('group', { name: 'Bisherige Adresse' }).getByLabel('PLZ', { exact: true }).click();
  await page.getByRole('group', { name: 'Bisherige Adresse' }).getByLabel('PLZ', { exact: true }).fill('12345');
  await page.getByRole('group', { name: 'Bisherige Adresse' }).getByLabel('Ort', { exact: true }).click();
  await page.getByRole('group', { name: 'Bisherige Adresse' }).getByLabel('Ort', { exact: true }).fill('12');
  await page.getByRole('group', { name: 'Bisherige Adresse' }).getByLabel('Straße').click();
  await page.getByRole('group', { name: 'Bisherige Adresse' }).getByLabel('Straße').fill('here st');
  await page.getByRole('group', { name: 'Bisherige Adresse' }).getByLabel('Straße').press('Tab');
  await page.getByRole('group', { name: 'Bisherige Adresse' }).getByLabel('Nr.', { exact: true }).fill('1');
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('PLZ', { exact: true }).click();
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('PLZ', { exact: true }).fill('12346');
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('PLZ', { exact: true }).press('Tab');
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('Ort', { exact: true }).fill('dw');
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('Straße').click();
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('Straße').fill('1');
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('Straße').press('Tab');
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('Nr.', { exact: true }).fill('1');
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('Straße').dblclick();
  await page.getByRole('group', { name: 'Neue Adresse' }).getByLabel('Straße').fill('fer');
  await page.getByRole('textbox', { name: 'Adresszusatz (optional)', exact: true }).click();
  await page.getByRole('textbox', { name: 'Vorname' }).click();
  await page.getByRole('textbox', { name: 'Vorname' }).fill('adr');
  await page.getByRole('textbox', { name: 'Vorname' }).press('Tab');
  await page.getByRole('textbox', { name: 'Nachname' }).fill('asderv');
  await page.getByRole('textbox', { name: 'Beginn der Nachsendung' }).click();
  await page.getByLabel('13.03.2025').click();
  await page.getByRole('textbox', { name: 'Beginn der Nachsendung' }).fill('13.03.2025');
  await page.getByRole('textbox', { name: 'Beginn der Nachsendung' }).click();
  await page.getByLabel('11.03.2025').click();
  await page.getByText('Mit Umzugsmitteilungohne Mehrkosten Tipp').click();
  await page.getByRole('link', { name: 'In den Warenkorb' }).click();
  await page.getByRole('link', { name: 'Weiter einkaufen' }).click();
  await page.goto('https://shop.deutschepost.de/shop/warenkorb/index.jsp?_requestid=1313001');
  await page.getByRole('link', { name: 'Nächster Schritt' }).click();
  await page.getByRole('button', { name: 'als Besucher weiter surfen' }).click();
  await page.goto('https://shop.deutschepost.de/shop/warenkorb/index.jsp?_requestid=1313001');
});